### ISSUE TITLE
Provider crash on dnacenter_wireless_provision_access_point

### ISSUE THREAD

**Issue by pamosima** [cisco-en-programmability/terraform-provider-dnacenter#140]
**Prerequisites**
* [X] Have you tested the operation in the API directly?
* [X] Do you have the latest Terraform provider version?
* [X] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
Provider crashes when running terraform apply:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.m3_wireless.dnacenter_wireless_provision_access_point.ap will be created
  + resource "dnacenter_wireless_provision_access_point" "ap" {
      + id           = (known after apply)
      + item         = (known after apply)
      + last_updated = (known after apply)

      + parameters {
          + payload {
              + device_name         = "zh-ap-1"
              + rf_profile          = "TYPICAL"
              + site_id             = "Global/DevNet/Zurich/ZH-1/ZH-1-1"
              + site_name_hierarchy = "Global/DevNet/Zurich/ZH-1/ZH-1-1"
              + type                = "ApWirelessConfiguration"
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Saved the plan to: general.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "general.tfplan"
admin@ubuntu2204:~/DevNet_Terraform-Workshop/examples/infra/example_devnet_zurich$ terraform apply "general.tfplan"
module.m3_wireless.dnacenter_wireless_provision_access_point.ap: Creating...
╷
│ Error: Request cancelled
│ 
│   with module.m3_wireless.dnacenter_wireless_provision_access_point.ap,
│   on ../../modules/m3_wireless/dnacenter_wireless_provision_ap.tf line 16, in resource "dnacenter_wireless_provision_access_point" "ap":
│   16: resource "dnacenter_wireless_provision_access_point" "ap" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-dnacenter_v1.0.18-beta plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 11 [running]:
terraform-provider-dnacenter/dnacenter.resourceWirelessProvisionAccessPointCreate({0x16bca28, 0xc00007b9e0}, 0xc000e256c0, {0x132cde0, 0xc000d78500})
        terraform-provider-dnacenter/dnacenter/resource_wireless_provision_access_point.go:147 +0xe9e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000519a40, {0x16bc9b8, 0xc0000b1b80}, 0x2, {0x132cde0, 0xc000d78500})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:341 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000519a40, {0x16bc9b8, 0xc0000b1b80}, 0xc000ad4c30, 0xc000d96900, {0x132cde0, 0xc000d78500})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000c030, {0x16bc9b8, 0xc0000b1b80}, 0xc000972730)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000f0d00, {0x16bca60, 0xc00105e1e0}, 0xc000d5c000)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x13f23c0, 0xc0000f0d00}, {0x16bca60, 0xc00105e1e0}, 0xc00007a5a0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022b180, {0x16d03d8, 0xc00082a000}, 0xc00076e000, 0xc0007d34d0, 0x1dea000, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc00022b180, {0x16d03d8, 0xc00082a000}, 0xc00076e000, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x294

Error: The terraform-provider-dnacenter_v1.0.18-beta plugin crashed!
```

**Expected behavior**
Provider is not supposed to crash.

**Screenshots**
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/16715420/222369161-16b937ce-8f38-49eb-bfc5-f8a0a916b7b9.png">

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.3.4
* Terraform version: 1.3.9
* Cisco DNA Center provider version: 1.0.18-beta
* OS Version: Ubuntu 22.04.1

**Additional context**
[terraform.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/10868957/terraform.log)
[dnacenter_wireless_provision_ap.tf.txt](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/10868962/dnacenter_wireless_provision_ap.tf.txt)

**Comment by fmunozmiranda** [comment]
@pamosima please try it again with new version(v1.0.19-beta) and let us know how does it go.

**Comment by fmunozmiranda** [comment]
Hey @pamosima , If we do not receive a response from you in the next 24 hours, the issue will be closed.

**Comment by fmunozmiranda** [comment]
Hi @pamosima please try it again with v1.1.0-beta

**Comment by fmunozmiranda** [comment]
Hi @pamosima could you confirm if it worked for you?

If we do not receive a response, the issue will be closed in the next 24 hours.
