### ISSUE TITLE
Usasge of `data.dnacenter_site` datasource causes provider panic

### ISSUE THREAD

**Issue by mschedrin** [cisco-en-programmability/terraform-provider-dnacenter#204]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
Since version 1.1.13 `data.dnacenter_site` causes provider panic. Version 1.1.14 is also affected. 
Datasource configuration:
```
data "dnacenter_site" "global" {
  provider = dnacenter
  limit    = 1
  name     = "Global"
}
```
Output from terraform apply:
```
> terraform apply -target dnacenter_network_create.this
data.dnacenter_site.global: Reading...
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as
│ part of an error message.
╵
╷
│ Error: Plugin did not respond
│ 
│   with data.dnacenter_site.global,
│   on site_hierarchy.tf line 45, in data "dnacenter_site" "global":
│   45: data "dnacenter_site" "global" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with dnacenter_area.l1["MINIHF"],
│   on site_hierarchy.tf line 52, in resource "dnacenter_area" "l1":
│   52: resource "dnacenter_area" "l1" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

Stack trace from the terraform-provider-dnacenter_v1.1.14-beta plugin:

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 86 [running]:
terraform-provider-dnacenter/dnacenter.dataSourceSiteRead({0x180d0a0?, 0xc000c556e0?}, 0x0?, {0x141fee0?, 0xc0000bc160})
        terraform-provider-dnacenter/dnacenter/data_source_site.go:167 +0x70b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000725ce0, {0x180d0a0, 0xc000c556e0}, 0xd?, {0x141fee0, 0xc0000bc160})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:750 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000725ce0, {0x180d0a0, 0xc000c556e0}, 0xc000763180, {0x141fee0, 0xc0000bc160})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:970 +0x150
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000118048, {0x180d0a0?, 0xc000c555c0?}, 0xc000cd83e0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:1198 +0x38f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc00038a0a0, {0x180d0a0?, 0xc000c54c30?}, 0xc000be0fa0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:661 +0x3ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x14f4c80?, 0xc00038a0a0}, {0x180d0a0, 0xc000c54c30}, 0xc00075e230, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:458 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000476000, {0x180fdc0, 0xc000322680}, 0xc000bd9d40, 0xc000ac2930, 0x1ef4550, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1360 +0xe13
google.golang.org/grpc.(*Server).handleStream(0xc000476000, {0x180fdc0, 0xc000322680}, 0xc000bd9d40, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1737 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.0/server.go:982 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.57.0/server.go:980 +0x18c

Error: The terraform-provider-dnacenter_v1.1.14-beta plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
Terraform log: [dnac.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/12551203/dnac.log)

**Expected behavior**
No panic expected. 

**Screenshots**
Not relevant

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.5.3-70194
* Terraform version: 1.5.0
* Cisco DNA Center provider version: 1.1.12-beta
* OS Version: Ubuntu 20.04

**Comment by fmunozmiranda** [comment]
Hey @mschedrin ,Due to the changes for the idempotence of the site resource, a possible null had not been contemplated, it was already contemplated, it should work now, try it and tell us.
Thank you.

**Comment by mschedrin** [comment]
It work show, thanks.
