### ISSUE TITLE
Provider does not detect changes in resource `dnacenter_configuration_template` made outside of terraform

### ISSUE THREAD

**Issue by mschedrin** [cisco-en-programmability/terraform-provider-dnacenter#211]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
DNAC provider does not detect changes made to configuration templates outside of terraform, for example in DNAC web interface. Currently the provider uses `GET /dna/intent/api/v1/template-programmer/project?name=<project name>` when it refreshes state for resource `dnacenter_configuration_template`, this call does not return template contents as well as many other details. Correct API request for refreshing state should be `GET /dna/intent/api/v1/template-programmer/template/<template-id>`.
Debug log for `terraform refresh`: [dnac.sanitized.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/12717825/dnac.sanitized.log)
Example output from `GET /dna/intent/api/v1/template-programmer/template/<template-id>` : 
```
{
    "name": "tf_template_test2",
    "description": "Terraform takes over humans",
    "tags": [],
    "author": "admin",
    "deviceTypes": [
        {
            "productFamily": "Switches and Hubs",
            "productSeries": "Cisco Catalyst 9300 Series Switches"
        }
    ],
    "softwareType": "IOS-XE",
    "softwareVariant": "XE",
    "softwareVersion": "17.06.03",
    "templateContent": "hello\nline number 2\nline number 3\n",
    "templateParams": [],
    "rollbackTemplateParams": [],
    "composite": false,
    "containingTemplates": [],
    "language": "VELOCITY",
    "id": "57f61371-2805-4351-8dba-cf1b3e47f49c",
    "customParamsOrder": false,
    "createTime": 1695660686152,
    "lastUpdateTime": 1695661748160,
    "latestVersionTime": 0,
    "projectName": "Onboarding Configuration",
    "projectId": "026bc13b-4616-4f38-9dc5-0a5d57cf0d39",
    "parentTemplateId": "57f61371-2805-4351-8dba-cf1b3e47f49c",
    "validationErrors": {
        "templateErrors": [],
        "rollbackTemplateErrors": [],
        "templateId": "57f61371-2805-4351-8dba-cf1b3e47f49c",
        "templateVersion": null
    },
    "noOfConflicts": 0,
    "documentDatabase": false,
    "projectAssociated": true
}
```
Template contents can be found in `templateContent`, but please do state verification for all the fields. 
Here is terraform state for the same configuration template:
```
> terraform state show dnacenter_configuration_template.onboarding_border[\"test.yml\"]
# dnacenter_configuration_template.onboarding_border["test.yml"]:
resource "dnacenter_configuration_template" "onboarding_border" {
    id   = "project_id:=026bc13b-4616-4f38-9dc5-0a5d57cf0d39\\project_name:=Onboarding Configuration\\template_id:=57f61371-2805-4351-8dba-cf1b3e47f49c\\template_name:=tf_template_test2"
    item = [
        {
            author                    = ""
            composite                 = "false"
            containing_templates      = []
            create_time               = 0
            custom_params_order       = "false"
            description               = ""
            device_types              = []
            failure_policy            = ""
            id                        = "57f61371-2805-4351-8dba-cf1b3e47f49c"
            language                  = "VELOCITY"
            last_update_time          = 1695661748160
            latest_version_time       = 0
            name                      = "tf_template_test2"
            parent_template_id        = ""
            project_id                = "026bc13b-4616-4f38-9dc5-0a5d57cf0d39"
            project_name              = "Onboarding Configuration"
            rollback_template_content = ""
            rollback_template_params  = []
            software_type             = ""
            software_variant          = ""
            software_version          = ""
            tags                      = []
            template_content          = ""
            template_params           = []
            validation_errors         = []
            version                   = ""
        },
    ]

    parameters {
        author              = "Terraform"
        composite           = "false"
        create_time         = 0
        custom_params_order = "false"
        description         = "Terraform takes over humans"
        language            = "VELOCITY"
        last_update_time    = 0
        latest_version_time = 0
        name                = "tf_template_test2"
        project_id          = "026bc13b-4616-4f38-9dc5-0a5d57cf0d39"
        project_name        = "Onboarding Configuration"
        software_type       = "IOS"
        software_variant    = "XE"
        software_version    = "17.06.03"
        template_content    = <<-EOT
            hello
            line number 2
            line number 3
        EOT

        device_types {
            product_family = "Switches and Hubs"
            product_series = "Cisco Catalyst 9300 Series Switches"
        }
    }
}
```

I can send you API mocks if this can help. 

**Expected behavior**
Changes are detected and overwritten by terraform. 

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.5.4-70852
* Terraform version: 1.5.6
* Cisco DNA Center provider version: 1.1.17-beta
* OS Version: Ubuntu 20.04

**Comment by fmunozmiranda** [comment]
Hey @mschedrin, I make some changes to have this behavior, setting parameters with API answer, could you please try it again and notify us, thanks.

**Comment by mschedrin** [comment]
@fmunozmiranda , thanks for attempting to fix that. The issue has got new symptoms: provider crashes upon creation of the resource. Would you be so kind to consider testing the code locally before releasing it? I can provide API mocks in order to facilitate testing. 
Terraform log: [dnac.sanitized.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/12765083/dnac.sanitized.log)

Terraform output:
```
dnacenter_configuration_template.this["logging"]: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with dnacenter_configuration_template.this["logging"],
│   on main.tf line 36, in resource "dnacenter_configuration_template" "this":
│   36: resource "dnacenter_configuration_template" "this" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-dnacenter_v1.1.18-beta plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe8706c]

goroutine 22 [running]:
terraform-provider-dnacenter/dnacenter.resourceConfigurationTemplateCreate({0x18137e8, 0xc0013b0720}, 0x0?, {0x1424f80?, 0xc0000bc160?})
        terraform-provider-dnacenter/dnacenter/resource_configuration_template.go:2265 +0x9ec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000512ee0, {0x1813820, 0xc000c2d230}, 0xd?, {0x1424f80, 0xc0000bc160})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:733 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000512ee0, {0x1813820, 0xc000c2d230}, 0xc0005488f0, 0xc0010e1180, {0x1424f80, 0xc0000bc160})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:864 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002fa018, {0x1813820?, 0xc000c2d050?}, 0xc000d34cd0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:1024 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000236000, {0x1813820?, 0xc000c2c780?}, 0xc000e2e620)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:821 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x14f9d20?, 0xc000236000}, {0x1813820, 0xc000c2c780}, 0xc000e2e5b0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000003c0, {0x1816540, 0xc000525d40}, 0xc000d7d8c0, 0xc000a76960, 0x1efb520, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1360 +0xe13
google.golang.org/grpc.(*Server).handleStream(0xc0000003c0, {0x1816540, 0xc000525d40}, 0xc000d7d8c0, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1737 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.0/server.go:982 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.57.0/server.go:980 +0x18c

Error: The terraform-provider-dnacenter_v1.1.18-beta plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by mschedrin** [comment]
Version 1.1.21 crashes on resource creation too:
```
dnacenter_configuration_template_project.dayN: Creating...
dnacenter_configuration_template_project.dayN: Creation complete after 5s [id=name:=DayN Templates]
data.dnacenter_configuration_template_project.all: Reading...
data.dnacenter_configuration_template_project.all: Read complete after 0s [id=1696861037]
dnacenter_configuration_template.this["logging"]: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with dnacenter_configuration_template.this["logging"],
│   on main.tf line 36, in resource "dnacenter_configuration_template" "this":
│   36: resource "dnacenter_configuration_template" "this" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with dnacenter_configuration_template.this["Onboarding Border"],
│   on main.tf line 36, in resource "dnacenter_configuration_template" "this":
│   36: resource "dnacenter_configuration_template" "this" {
│ 
│ The plugin.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵

Stack trace from the terraform-provider-dnacenter_v1.1.21 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe8706c]

goroutine 74 [running]:
terraform-provider-dnacenter/dnacenter.resourceConfigurationTemplateCreate({0x1813688, 0xc001364660}, 0x0?, {0x1424f80?, 0xc000370b00?})
        terraform-provider-dnacenter/dnacenter/resource_configuration_template.go:2265 +0x9ec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0000f4e00, {0x18136c0, 0xc00103e570}, 0xd?, {0x1424f80, 0xc000370b00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:733 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000f4e00, {0x18136c0, 0xc00103e570}, 0xc000553ba0, 0xc0014f6e80, {0x1424f80, 0xc000370b00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:864 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000124078, {0x18136c0?, 0xc00103e450?}, 0xc000da2b40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:1024 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00012c0a0, {0x18136c0?, 0xc000da5bf0?}, 0xc0014289a0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:821 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x14f9d20?, 0xc00012c0a0}, {0x18136c0, 0xc000da5bf0}, 0xc001428930, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00038a000, {0x18163e0, 0xc000558680}, 0xc000db05a0, 0xc000a78930, 0x1efb520, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1360 +0xe13
google.golang.org/grpc.(*Server).handleStream(0xc00038a000, {0x18163e0, 0xc000558680}, 0xc000db05a0, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1737 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.0/server.go:982 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.57.0/server.go:980 +0x18c

Error: The terraform-provider-dnacenter_v1.1.21 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by fmunozmiranda** [comment]
Hi @mschedrin, A possible null is due controlled, please try again with 1.1.22-beta, thank you.

**Comment by mschedrin** [comment]
Now it works as expected. Thank you.
